version: '3'
services:

  workspace:
    build:
      context: .
      dockerfile: ./docker/php-fpm/Dockerfile
    restart: always
    volumes:
      - ./app:/var/www/app
    networks:
      - project
    working_dir: /var/www

  # nginx
  nginx:
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    restart: always
    ports:
      - 7700:80
    volumes:
      - ./app:/var/www/app
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - project
    working_dir: /var/www

networks:
  project:
    name: laradock_backend
    external: true

